# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\x12\tPB.Simple\"\xab\x01\n\x15SimpleProtoBufMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x41\n\x0bmessageType\x18\x03 \x01(\x0e\x32,.PB.Simple.SimpleProtoBufMessage.MessageType\"2\n\x0bMessageType\x12\x08\n\x04PING\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x42\x14\n\x12\x63om.model.protobufb\x06proto3')



_SIMPLEPROTOBUFMESSAGE = DESCRIPTOR.message_types_by_name['SimpleProtoBufMessage']
_SIMPLEPROTOBUFMESSAGE_MESSAGETYPE = _SIMPLEPROTOBUFMESSAGE.enum_types_by_name['MessageType']
SimpleProtoBufMessage = _reflection.GeneratedProtocolMessageType('SimpleProtoBufMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEPROTOBUFMESSAGE,
  '__module__' : 'address_pb2'
  # @@protoc_insertion_point(class_scope:PB.Simple.SimpleProtoBufMessage)
  })
_sym_db.RegisterMessage(SimpleProtoBufMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.model.protobuf'
  _SIMPLEPROTOBUFMESSAGE._serialized_start=29
  _SIMPLEPROTOBUFMESSAGE._serialized_end=200
  _SIMPLEPROTOBUFMESSAGE_MESSAGETYPE._serialized_start=150
  _SIMPLEPROTOBUFMESSAGE_MESSAGETYPE._serialized_end=200
# @@protoc_insertion_point(module_scope)
